version: "3.7"
services:
  app:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    container_name: webserver
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

